mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('obfus/', include('obfus.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

mysite/obfus/urls.py
from django.urls import path

from . import views
from .views import CreatePostView

app_name="obfus"

urlpatterns = [
    #ex: /obfus/
    path('', CreatePostView.as_view(), name='add_post'),
    path('<int:participant_num>/', views.postDetail, name='post_detail'),
    path('<int:participant_num>/deepfake/', views.viewPicDeepfake, name='deepfake'),
    path('<int:participant_num>/pixelated/', views.viewPicPixelated, name='pixelated'),
    path('<int:participant_num>/blurred/', views.viewPicBlurred, name='blurred'),
    path('<int:participant_num>/masked/', views.viewPicMasked, name='masked'),
    path('<int:participant_num>/asis/', views.viewPicAsIs, name='asis'),
    path('<int:participant_num>/avatar/', views.viewPicAvatar, name='avatar'),
    path('<int:participant_num>/bystander_deepfake/', views.viewPicDeepfakeBystander, name='bystander_deepfake'),
    path('<int:participant_num>/bystander_pixelated/', views.viewPicPixelatedBystander, name='bystander_pixelated'),
    path('<int:participant_num>/bystander_blurred/', views.viewPicBlurredBystander, name='bystander_blurred'),
    path('<int:participant_num>/bystander_masked/', views.viewPicMaskedBystander, name='bystander_masked'),
    path('<int:participant_num>/bystander_asis/', views.viewPicAsIsBystander, name='bystander_asis'),
    path('<int:participant_num>/bystander_avatar/', views.viewPicAvatarBystander, name='bystander_avatar')
]

mysite/obfus/models.py
from django.db import models

# Create your models here.
class Participant(models.Model):
    GENDER_CHOICES = [('Male', 'Male'),
                      ('Female', 'Female')]
    SKIN_TONE = [('Light', 'Light'),
                 ('Dark', 'Dark')]

    participant_num = models.IntegerField('participant number', unique=True)
    participant_pic = models.ImageField(upload_to='images/')
    not_participant_pic = models.ImageField(upload_to='images/')
    gender = models.CharField(max_length=64, choices=GENDER_CHOICES, default="")
    skin_tone = models.CharField(max_length=64, choices=SKIN_TONE, default="")
    participant_pic_left = models.ImageField(upload_to='images/cropped/', blank=True)
    not_participant_pic_left = models.ImageField(upload_to='images/cropped/', blank=True)
    participant_pic_right = models.ImageField(upload_to='images/cropped/', blank=True)
    not_participant_pic_right = models.ImageField(upload_to='images/cropped/', blank=True)
    deepfake_obfus = models.ImageField(upload_to='images/deepfake', blank=True)
    blurred_obfus = models.ImageField(upload_to='images/blurred', blank=True)
    pixelated_obfus = models.ImageField(upload_to='images/pixelated', blank=True)
    masked_obfus = models.ImageField(upload_to='images/masked', blank=True)
    avatar_obfus = models.ImageField(upload_to='images/avatar', blank=True)
    bystander_deepfake_obfus = models.ImageField(upload_to='images/deepfake', blank=True)
    bystander_blurred_obfus = models.ImageField(upload_to='images/blurred', blank=True)
    bystander_pixelated_obfus = models.ImageField(upload_to='images/pixelated', blank=True)
    bystander_masked_obfus = models.ImageField(upload_to='images/masked', blank=True)
    bystander_avatar_obfus = models.ImageField(upload_to='images/avatar', blank=True)

    def __str__(self):
        return str(self.participant_num)

mysite/obfus/forms.py
from django import forms
from .models import Participant



class PostForm(forms.ModelForm):
    class Meta:
        model = Participant
        fields = ['participant_num', 'participant_pic', 'not_participant_pic', 'gender', 'skin_tone']
        labels = {
            'participant_num': 'Participant Number',
            'participant_pic': "Participant's Picture",
            'not_participant_pic': "Bystander's Picture",
            'gender': 'Gender',
            'skin_tone': 'Skin Tone'
        }

mysite/obfus/views.py
from .models import Participant
from django.views.generic import CreateView
from .forms import PostForm
from django.shortcuts import redirect
from django.shortcuts import render
from PIL import Image
from django.conf import settings
import logging
import os
import cv2
from django.contrib.staticfiles.storage import staticfiles_storage
import numpy as np

logger = logging.getLogger(__name__)


# Create your views here.
class CreatePostView(CreateView):
    model = Participant
    form_class = PostForm
    template_name = 'obfus/post.html'

    def form_valid(self, form):
        form.save()
        part_num = form.cleaned_data.get('participant_num')
        return redirect('obfus:post_detail', part_num)


def viewPicDeepfake(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    context = {'participant_pic': participant.deepfake_obfus.url, "participant_num": participant.participant_num}
    return render(request, 'obfus/detail.html', context)


def viewPicBlurred(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    context = {'participant_pic': participant.blurred_obfus.url, "participant_num": participant.participant_num}
    return render(request, 'obfus/detail.html', context)


def viewPicPixelated(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    context = {'participant_pic': participant.pixelated_obfus.url, "participant_num": participant.participant_num}
    return render(request, 'obfus/detail.html', context)


def viewPicMasked(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    context = {'participant_pic': participant.masked_obfus.url, "participant_num": participant.participant_num}
    return render(request, 'obfus/detail.html', context)


def viewPicAsIs(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    context = {'participant_pic': participant.participant_pic.url, "participant_num": participant.participant_num}
    return render(request, 'obfus/detail.html', context)

def viewPicAvatar(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    context = {'participant_pic': participant.avatar_obfus.url, "participant_num": participant.participant_num}
    return render(request, 'obfus/detail.html', context)

def viewPicDeepfakeBystander(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    context = {'participant_pic': participant.bystander_deepfake_obfus.url, "participant_num": participant.participant_num}
    return render(request, 'obfus/detail.html', context)


def viewPicBlurredBystander(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    context = {'participant_pic': participant.bystander_blurred_obfus.url, "participant_num": participant.participant_num}
    return render(request, 'obfus/detail.html', context)


def viewPicPixelatedBystander(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    context = {'participant_pic': participant.bystander_pixelated_obfus.url, "participant_num": participant.participant_num}
    return render(request, 'obfus/detail.html', context)


def viewPicMaskedBystander(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    context = {'participant_pic': participant.bystander_masked_obfus.url, "participant_num": participant.participant_num}
    return render(request, 'obfus/detail.html', context)


def viewPicAsIsBystander(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    context = {'participant_pic': participant.not_participant_pic.url, "participant_num": participant.participant_num}
    return render(request, 'obfus/detail.html', context)

def viewPicAvatarBystander(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    context = {'participant_pic': participant.bystander_avatar_obfus.url, "participant_num": participant.participant_num}
    return render(request, 'obfus/detail.html', context)


def postDetail(request, participant_num):
    participant = Participant.objects.get(participant_num=participant_num)
    image = Image.open(participant.participant_pic)
    bystander_image = Image.open(participant.not_participant_pic)
    path_to_cropped = settings.MEDIA_ROOT + "\\images\\cropped\\"
    width, height = image.size
    bystander_width, bystander_height = bystander_image.size
    filename = participant.participant_pic.url[participant.participant_pic.url.rfind("/") + 1:]
    bystander_filename = participant.not_participant_pic.url[participant.not_participant_pic.url.rfind("/") + 1:]
    left_image = image.crop(((0, 0, width / 2, height)))
    right_image = image.crop(((width / 2, 0, width, height)))
    bystander_left_image = bystander_image.crop(((0, 0, bystander_width / 2, bystander_height)))
    bystander_right_image = bystander_image.crop(((bystander_width / 2, 0, bystander_width, bystander_height)))
    left_url = path_to_cropped + filename.replace(".", "_left.")
    right_url = path_to_cropped + filename.replace(".", "_right.")
    bystander_left_url = path_to_cropped + bystander_filename.replace(".", "_left.")
    bystander_right_url = path_to_cropped + bystander_filename.replace(".", "_right.")
    left_image.save(left_url)
    right_image.save(right_url)
    bystander_left_image.save(bystander_left_url)
    bystander_right_image.save(bystander_right_url)
    participant.participant_pic_left = left_url
    participant.participant_pic_right = right_url
    participant.not_participant_pic_left = bystander_left_url
    participant.not_participant_pic_right = bystander_right_url
    participant.save()

    if not participant.avatar_obfus:
        print("Running avatar")
        path_final = get_avatar(left_url, participant, filename, right_image)
        participant.avatar_obfus = path_final

    if not participant.bystander_avatar_obfus:
        print("Running bystander avatar")
        path_final = get_avatar(bystander_left_url, participant, bystander_filename, bystander_right_image)
        participant.bystander_avatar_obfus = path_final

    if not participant.deepfake_obfus:
        print("Running deepfake")
        path_final = get_deepfake(left_url, participant, filename, right_image)
        participant.deepfake_obfus = path_final

    if not participant.bystander_deepfake_obfus:
        print("Running bystander deepfake")
        path_final = get_deepfake(bystander_left_url, participant, bystander_filename, bystander_right_image)
        participant.bystander_deepfake_obfus = path_final

    if not participant.blurred_obfus:
        print("Running blurred")
        path_final = get_blurred(participant, left_url, filename, right_image)
        participant.blurred_obfus = path_final

    if not participant.bystander_blurred_obfus:
        print("Running bystander blurred")
        path_final = get_blurred(participant, bystander_left_url, bystander_filename, bystander_right_image)
        participant.bystander_blurred_obfus = path_final

    if not participant.pixelated_obfus:
        print("Running pixelated")
        path_final = get_pixelated(participant, left_url, filename, right_image)
        participant.pixelated_obfus = path_final

    if not participant.bystander_pixelated_obfus:
        print("Running bystander pixelated")
        path_final = get_pixelated(participant, bystander_left_url, bystander_filename, bystander_right_image)
        participant.bystander_pixelated_obfus = path_final

    if not participant.masked_obfus:
        print("Running masked")
        path_final = get_masked(participant, left_url, filename, right_image)
        participant.masked_obfus = path_final

    if not participant.bystander_masked_obfus:
        print("Running bystander masked")
        path_final = get_masked(participant, bystander_left_url, bystander_filename, bystander_right_image)
        participant.bystander_masked_obfus = path_final

    participant.save()

    context = {'participant': participant}
    return render(request, 'obfus/index.html', context)


def get_deepfake(left_url, participant, filename, right_image):
    path_to_deepfake = settings.MEDIA_ROOT + "\\images\\deepfake\\"
    path_deep = os.path.join(path_to_deepfake, filename.replace(".", "_deepfake_left."))
    path_deep_final = os.path.join(path_to_deepfake, filename.replace(".", "_deepfake."))
    command = "C:/Users/dom/Desktop/deepFakePrivacyProtector/mysite/DeepPrivacy/deep.bat " \
              + left_url + " " + path_deep
    os.system(command)
    image_left_deepfake = Image.open(path_deep)
    image_deepfake = get_concat_h(image_left_deepfake, right_image)
    image_deepfake.save(path_deep_final)
    return path_deep_final



def get_avatar(left_url, participant, filename, right_image):
    path_to_avatar = settings.MEDIA_ROOT + "\\images\\avatar\\"
    path_avatar_left = os.path.join(path_to_avatar, filename.replace(".", "_avatar_left."))
    path_avatar_final = os.path.join(path_to_avatar, filename.replace(".", "_avatar."))

    if participant.gender == "Male" and participant.skin_tone == "Light":
        pic_url = staticfiles_storage.path('images/lightmale.png')
        avatar_image = cv2.imread(pic_url, cv2.IMREAD_UNCHANGED)
    if participant.gender == "Male" and participant.skin_tone == "Dark":
        pic_url = staticfiles_storage.path('images/darkmale.png')
        avatar_image = cv2.imread(pic_url, cv2.IMREAD_UNCHANGED)
    if participant.gender == "Female" and participant.skin_tone == "Light":
        pic_url = staticfiles_storage.path('images/lightfemale.png')
        avatar_image = cv2.imread(pic_url, cv2.IMREAD_UNCHANGED)

mysite/obfus/templates/obfus/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<img style="max-width: 60%; max-height: 60%;" src="{{ participant_pic }}">

<form action='actionUrl' method='GET'>
        <input style=" position:absolute;bottom: 5%;right:20%;" t type="button" value="Return" onclick="location.href='{% url 'obfus:post_detail' participant_num=participant_num %}'"  />
</form>

mysite/obfus/templates/obfus/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<h1>Participant - {{ participant.participant_num }}</h1>

<h2>Owned Pictures (Bystanders)</h2>

<div class="buttons_horizontal">
    <form action='deepfake' method='GET'>
        <input  type="button" value="Deepfake" onclick="location.href='{% url 'obfus:deepfake' participant_num=participant.participant_num %}'"  />
    </form>

    <form action='actionUrl' method='GET'>
        <input type="button" value="Masking" onclick="location.href='{% url 'obfus:masked' participant_num=participant.participant_num %}'"  />
    </form>

    <form action='actionUrl' method='GET'>
        <input type="button" value="Pixelating" onclick="location.href='{% url 'obfus:pixelated' participant_num=participant.participant_num %}'"  />
    </form>

    <form action='actionUrl' method='GET'>
        <input type="button" value="Blurring" onclick="location.href='{% url 'obfus:blurred' participant_num=participant.participant_num %}'"  />
    </form>

    <form action='actionUrl' method='GET'>
        <input type="button" value="Avatar" onclick="location.href='{% url 'obfus:avatar' participant_num=participant.participant_num %}'"  />
    </form>

    <form action='actionUrl' method='GET'>
        <input type="button" value="As Is (No obfuscation)" onclick="location.href='{% url 'obfus:asis' participant_num=participant.participant_num %}'"  />
    </form>
</div>

<br>
<br>
<br>
<br>
<br>
<h2>Unowned Pictures (Participants)</h2>
<div class="buttons_horizontal">
    <form action='deepfake' method='GET'>
        <input  type="button" value="Deepfake" onclick="location.href='{% url 'obfus:bystander_deepfake' participant_num=participant.participant_num %}'"  />
    </form>

    <form action='actionUrl' method='GET'>
        <input type="button" value="Masking" onclick="location.href='{% url 'obfus:bystander_masked' participant_num=participant.participant_num %}'"  />
    </form>

    <form action='actionUrl' method='GET'>
        <input type="button" value="Pixelating" onclick="location.href='{% url 'obfus:bystander_pixelated' participant_num=participant.participant_num %}'"  />
    </form>

    <form action='actionUrl' method='GET'>
        <input type="button" value="Blurring" onclick="location.href='{% url 'obfus:bystander_blurred' participant_num=participant.participant_num %}'"  />
    </form>

    <form action='actionUrl' method='GET'>
        <input type="button" value="Avatar" onclick="location.href='{% url 'obfus:bystander_avatar' participant_num=participant.participant_num %}'"  />
    </form>

    <form action='actionUrl' method='GET'>
        <input type="button" value="As Is (No obfuscation)" onclick="location.href='{% url 'obfus:bystander_asis' participant_num=participant.participant_num %}'"  />
    </form>
</div>

mysite/obfus/templates/obfus/post.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<form class="intro_form" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button style="margin: 0 auto; display: block;" type="submit">Submit New Post</button>
</form>